In [92]:
import pandas as pd
import numpy as np

### Q1 - Pandas Version

In [93]:
pd.__version__

'2.3.1'

### Q2 - Record Count

In [94]:
src_link = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

In [95]:
data = pd.read_csv(src_link)

In [96]:
data.shape

(9704, 11)

### Q3 - Fuel Types

In [97]:
data.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [98]:
data['fuel_type'].nunique()

2

### Q4 - Missing Values

In [99]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

### Q5 - Max fuel efficiency

In [100]:
data[data['origin'] == 'Asia'].fuel_efficiency_mpg.max().round(2)

np.float64(23.76)

### Q6 - Median value of horsepower

In [101]:
median_hp_before_replacement = data['horsepower'].median()
median_hp_before_replacement

np.float64(149.0)

In [102]:
hp_mode = data['horsepower'].mode()[0]
hp_mode

np.float64(152.0)

In [103]:
hp_after_replacement = data['horsepower'].fillna(hp_mode)
median_hp_after_replacement = hp_after_replacement.median()
median_hp_after_replacement

np.float64(152.0)

### Q7 - Sum of weights

In [104]:
asian_cars = data[data['origin']=='Asia']
asian_cars.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [105]:
subset = asian_cars[['vehicle_weight','model_year']]
subset.head(5)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [106]:
seven_records = subset.iloc[:7]
seven_records

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [107]:
X = seven_records.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [108]:
X_transpose = X.T
X_transpose

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [109]:
XTX = X_transpose.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [110]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [118]:
XTX_inv = np.linalg.inv(XTX)
w = (XTX_inv.dot(X_transpose)).dot(y)
w.sum()

np.float64(0.5187709081074016)