In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#full arguments are size of the array and the element you want to fill with
np.full(7,3)

array([3, 3, 3, 3, 3, 3, 3])

In [9]:
a = np.array([1,2,5,6,9,12])
a

array([ 1,  2,  5,  6,  9, 12])

In [10]:
a[5]

np.int64(12)

In [11]:
a[3] = 22
a

array([ 1,  2,  5, 22,  9, 12])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi dimensional array

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([[1,2,3],
              [2,3,4],
              [3,4,5]])


In [20]:
n[1,2]

np.int64(4)

In [25]:
n[1]

array([2, 3, 4])

In [26]:
n[:]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [18]:
n[:,2]

array([3, 4, 5])

In [19]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

## Randomly generated arrays

In [27]:
np.random.rand(10,3)

array([[0.71888947, 0.28200819, 0.49448552],
       [0.92939841, 0.95351543, 0.96874109],
       [0.30859969, 0.00630916, 0.67038031],
       [0.00267755, 0.07372397, 0.17874039],
       [0.15376497, 0.15151121, 0.93881401],
       [0.60353868, 0.89643901, 0.50940283],
       [0.34993611, 0.28311446, 0.96622363],
       [0.59081502, 0.20268249, 0.99100237],
       [0.22831932, 0.53210539, 0.96396542],
       [0.14084633, 0.65469576, 0.46895782]])

In [28]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
#NORMAL DISTRIBUTION
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size =  (5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

## Element-wise operations

In [2]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [3]:
a + 5

array([5, 6, 7, 8, 9])

In [7]:
b = a * 3

Comparison operations

In [6]:
a <= 2

array([ True,  True,  True, False, False])

In [8]:
a < b

array([False,  True,  True,  True,  True])

In [9]:
a[a < b]

array([1, 2, 3, 4])

In [10]:
b[a < b]

array([ 3,  6,  9, 12])

## Summarizing operations

In [11]:
a.min()

np.int64(0)

In [12]:
a.max()

np.int64(4)

In [13]:
a.mean()

np.float64(2.0)

In [14]:
a.sum()

np.int64(10)

In [15]:
a.std()

np.float64(1.4142135623730951)