## Vector operations

In [2]:
import numpy as np

In [3]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])


In [6]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [4]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [5]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

## Multiplication
### vector-vector multiplication

In [17]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n=u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [18]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [19]:
u.dot(v)

np.int64(110)

### matrix-vector multiplication

In [21]:
U = np.array([[1,2,3,4],
             [2,3,4,5],
             [3,4,5,6]])

In [31]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1]==v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)

    return result

In [32]:
matrix_vector_multiplication(U,v)

array([ 59.,  80., 101.])

In [33]:
U.dot(v)

array([ 59,  80, 101])

### matrix-matrix multiplication

In [39]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [1, 1, 1]
])

In [41]:
V.shape

(4, 3)

In [46]:
V[0]

array([1., 1., 2.])

In [47]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):

        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi

    return result
        

    

In [48]:
matrix_matrix_multiplication(U,V)

array([[ 5. , 12. , 11. ],
       [ 7. , 16.5, 16. ],
       [ 9. , 21. , 21. ]])

In [49]:
U.dot(V)

array([[ 5. , 12. , 11. ],
       [ 7. , 16.5, 16. ],
       [ 9. , 21. , 21. ]])

## Identity matrix

In [53]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [1. , 1. , 1. ]])

## Inverse

In [57]:
Vs = V[[0,1,2],:]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [58]:
Vs_inv = np.linalg.inv(Vs)

In [59]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])